apiVersion: v1
kind: ConfigMap
metadata:
  name: async-furious-config
  namespace: async-furious
data:
  NODE_ENV: "development"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_NAME: "workshop"
  DB_PORT: "5432"
  DB_USER: "postgres"
  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "repo-auth-serverless"
  JWT_AUDIENCE: "async-furious-project"
  JWT_EXPIRES_IN: "1800"
