apiVersion: v1
kind: ConfigMap
metadata:
  name: async-furious-config
  namespace: async-furious
data:
  NODE_ENV: "production"
  PORT: "3000"
  AUTH_MODE: "local"
  DEPLOY_ENV: "local"
  JWT_ISSUER: ""
  JWT_AUDIENCE: ""
  DB_NAME: "workshop"
  DB_USER: "postgres"
