apiVersion: v1
kind: Secret
metadata:
  name: async-furious-secret
  namespace: async-furious
type: Opaque
stringData:
  JWT_SECRET: "${jwt_secret}"
  POSTGRES_PASSWORD: "${db_password}"
  JWT_PUBLIC_KEY: "${jwt_public_key}"
  WEBHOOK_SECRET: "${webhook_secret}"
  DATABASE_URL: "${database_url}"
  DB_HOST: "${db_host}"
  DB_PORT: "${db_port}"
  DB_NAME: "${db_name}"
  DB_USER: "${db_user}"
  DB_PASSWORD: "${db_password}"
  DB_SSLMODE: "${db_sslmode}"
  SEED_ADMIN_EMAIL: "${seed_admin_email}"
  SEED_ADMIN_PASSWORD: "${seed_admin_password}"
