apiVersion: v1
kind: Secret
metadata:
  name: async-furious-secret
  namespace: async-furious
type: Opaque
stringData:
  JWT_SECRET: "${jwt_secret}"
  POSTGRES_PASSWORD: "${db_password}"
  DATABASE_URL: "postgresql://${db_user}:${db_password}@postgres-service:5432/${db_name}?schema=public"
  SEED_ADMIN_EMAIL: "${seed_admin_email}"
  SEED_ADMIN_PASSWORD: "${seed_admin_password}"
  SEED_RECEPCIONISTA_PASSWORD: "${seed_recepcionista_password}"
  SEED_MECANICO_PASSWORD: "${seed_mecanico_password}"
