apiVersion: v1
kind: ConfigMap
metadata:
  name: async-furious-config
  namespace: async-furious
data:
  NODE_ENV: "production"
  DB_HOST: "${DB_HOST}"
  JWT_ALGORITHM: "RS256"
  JWT_ISSUER: "repo-auth-serverless"
  JWT_AUDIENCE: "async-furious-project"
  JWT_EXPIRES_IN: "1800"
  KAFKA_CLIENT_ID: "async-furious-api"
  KAFKA_TOPIC_EVENTS: "os.eventos.v1"
  KAFKA_TOPIC_RETRY: "os.retry.v1"
  KAFKA_TOPIC_DLT: "os.dlt.v1"
