apiVersion: v1
kind: Service
metadata:
  name: async-furious-service
  namespace: async-furious
spec:
  type: ClusterIP
  selector:
    app: async-furious-api
  ports:
    - port: 3000
      targetPort: 3000
